name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify the PHP version you are using
          extensions: mbstring, pdo, pdo_mysql, openssl, json
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Serve the application
        run: |
          php artisan serve --host=0.0.0.0 --port=8000 > /dev/null 2>&1 &

      - name: Wait for server to start
        run: sleep 5

      - name: Ensure the application is running
        run: curl --fail http://127.0.0.1:8000 || exit 1
